const i18n = {
    en: {
        app_title: '<span class="gradient-text">Money Health</span> Mentor', app_desc: 'Get your AI-powered financial score and personalized action plan.',
        form_title: '📊 Financial Details', lbl_age: 'Age', lbl_income: 'Monthly Income (₹)', lbl_expenses: 'Monthly Expenses (₹)', lbl_emergency: 'Emergency Fund (Months covered)',
        lbl_health_ins: 'Health Insurance?', lbl_life_ins: 'Life Insurance (Term Plan)?', lbl_investments: 'Investment Diversification', lbl_tax: 'Tax Saving (80C)',
        lbl_debt: 'Do you have Debts/Loans?', lbl_emi: 'EMI % of Income', btn_analyze: 'Analyze My Finances 🚀', btn_recalc: 'Recalculate 🔄',
        status_analyzing: 'Analyzing...', status_good: 'GOOD', status_average: 'AVERAGE', status_poor: 'POOR',
        res_summary: '📌 Summary', res_problems: '⚠️ Top Problems', res_action: '✅ Action Plan', res_invest: '📈 Monthly Investment Suggestion', res_emergency: '🛡️ Emergency Fund Advice', res_tip: '💡 Smart Tip',
        opt_yes_personal: 'Yes (Personal)', opt_no_corp: 'No (Or Corporate only)', opt_yes: 'Yes', opt_no: 'No',
        opt_inv_none: 'None / Savings A/c', opt_inv_fd: 'FDs & PPF', opt_inv_mf: 'Mutual Funds & SIPs', opt_inv_stocks: 'Direct Equity / Stocks',
        opt_tax_yes: 'Yes (Maxed out ₹1.5L)', opt_tax_no: 'No / Not Fully utilized',
        
        rep_sum_good: "Your income and savings rate are very strong! You're on the right path to wealth creation. A little tuning will make it perfect.",
        rep_sum_avg: "Your income and savings are good, but planning for long-term safety (insurance/emergency) and investments is lacking. A few steps will easily put you in the 'Good' zone.",
        rep_sum_poor: "Your present financial habits are continuously creating risk. It's the best time to balance your income/expenses and get safeguards (insurance/funds).",
        rep_sum_alert: "Alert! Your expenses are higher than your income. Stopping unnecessary expenses is the most urgent task.",
        rep_prob_health: "Not having a Personal Health Insurance can wipe out all your savings and FDs in a major medical emergency.",
        rep_prob_life: "Not having a Term Life Insurance is a big risk, especially if your family depends on your income.",
        rep_prob_em: "Emergency fund of just {m} months is not enough to support you during a sudden job loss or crisis.",
        rep_prob_inv: "Keeping money only in bank accounts or FDs means inflation is slowly eating away your savings' purchasing power.",
        rep_prob_emi: "A huge chunk of your income ({p}%) is going towards paying EMIs.",
        rep_prob_none: "There are no major red flags right now! Just focus on returns to beat inflation.",
        rep_act_health: "As a backup, get a Base Health Insurance of at least ₹5L to ₹10L for yourself and your family as soon as possible.",
        rep_act_life: "Next step—get a pure Term Life Insurance (Coverage should be 10x to 15x your annual income).",
        rep_act_em: "Continuously save for your emergency fund until it reaches 6 months of expenses (₹{amt}) and keep it in a Liquid Mutual Fund.",
        rep_act_emi: "Try to clear off personal loans or credit card bills permanently via extra payments to fix your monthly cashflow.",
        rep_act_inv: "Start allocating some money into Equity Mutual Funds via SIP instead of sticking only to fixed-return assets!",
        rep_act_none: "Enjoy the compounding of your portfolio and increase your SIP by 10% every year as your income grows.",
        rep_inv_debt: "Right now, before starting investments, it's critical to pay off credit card or high-interest personal loans and cut unnecessary expenses.",
        rep_inv_good: "Suggested plan for you: Start a monthly SIP of ₹{sip} — ₹{n50} in a safe Nifty 50 Index Fund, ₹{flexi} in a Flexi Cap Fund and the remaining ₹{small} in an aggressive Small/Mid cap fund.",
        rep_inv_basic: "You can save around ₹{sav} from your budget. Simply start a SIP of at least ₹{amt} in a low-cost Index Fund. Increase it once it becomes a habit.",
        rep_em_adv: "A smart rule states you must save at least 6 months of your monthly expenses (₹{exp}). Target: ₹{tgt}. Keep this divided in Savings A/c and Liquid MFs, and don't touch it even in a market crash!",
        rep_tip: "Magic of Compounding: If you keep investing this ₹{sip} per month without skipping into Mutual Funds (approx 12-13% return class) for the next 15 years, you will effortlessly build a wealth corpus of over ₹{val}!",

        // TAX + COUPLE Specifics
        tab_health: '📊 Health Score', tab_tax: '⚖️ Tax Wizard', tab_couple: '👩‍❤️‍👨 Couple Planner',
        tax_title: '<span class="gradient-text">Tax</span> Wizard', tax_desc: 'AI models Old vs New Tax Regime to find your exact missing deductions for FY24-25.',
        tax_upload_text: '📄 Upload Form 16 / Salary Slip', tax_upload_sub: '(AI Vision Simulate Extraction)', tax_divider: 'OR ENTER DATA MANUALLY',
        tax_lbl_gross: 'Gross Annual Salary (₹)', tax_lbl_hra: 'HRA Exemption Claimed (₹)', tax_lbl_80c: '80C Deductions (ELSS, PF, LIC) (₹)',
        tax_lbl_80d: 'Health Ins. Premium (80D) (₹)', tax_lbl_hl: 'Home Loan Interest (₹)', tax_lbl_nps: 'NPS Additional (80CCD(1B)) (₹)',
        tax_lbl_oth: 'LTA / Other Exemptions (₹)', tax_btn_run: 'Run FinAI Tax Model ⚡', tax_res_new: 'New Tax Regime', tax_res_old: 'Old Tax Regime',
        tax_res_new_sub: '(Flat Standard Deduction)', tax_res_old_sub: '(With All Claimed Deductions)', tax_res_verdict: '🏆 FinAI Verdict', tax_res_advice: '💡 Missing Deductions & AI Optimization Advice',
        tax_sim_ext: '🔄 Extracting Data with AI...', tax_sim_succ: '✅ Data Extracted Successfully',
        tax_verd_old: '💡 The <b>Old Tax Regime</b> is better for you. You save ₹{diff} compared to the New Regime, because of your high deductions.',
        tax_verd_new: '💡 The <b>New Tax Regime</b> is better for you. You save ₹{diff}. Your current deductions are not high enough to beat the flat rates.',
        tax_verd_same: '💡 Both regimes yield the exact same tax. New Regime is less paperwork!',
        tax_adv_80c: '💰 Invest ₹{diff} more in ELSS/PF (80C) to max out exactly ₹1.5L limit.',
        tax_adv_nps: '🏦 Open an NPS Tier-1 account. Investing ₹50,000 gives you extra flat deduction under 80CCD(1B), saving up to ₹15,600!',
        tax_adv_80d: '🏥 Buy a comprehensive Health Insurance. You can claim up to ₹25,000 under 80D (₹50k for parents).',
        tax_adv_hra: '🏠 If you live on rent, properly submit rental agreements to increase your HRA exemption.',
        tax_adv_opt: '✨ You have completely optimized your taxes! No further deduction avenues available.',
        cpl_title: '<span class="gradient-text">Unified</span> Planner', cpl_desc: 'India\'s first AI-powered joint financial planning to optimize across two incomes seamlessly.',
        cpl_partner_a: '👩‍💼 Partner A', cpl_partner_b: '👨‍💼 Partner B', cpl_lbl_income: 'Annual In-Hand Income (₹)', cpl_lbl_80c: '80C Maxed Out? (₹1.5L)',
        cpl_lbl_hl: 'Home Loan EMI Burden (₹ Yearly)', cpl_lbl_sip: 'Monthly Joint Target Savings (SIPs, Goals) (₹)', cpl_btn_run: 'Optimize Unified Wealth 💍',
        cpl_res_title: '✅ Unified FinAI Optimization Strategy',
        cpl_adv_arb: '🏠 <b>Tax Arbitrage:</b> {p} is in a higher tax bracket ({slab}%). Ensure {p} claims the maximum possible Home Loan Interest (up to 2L) rather than splitting it equally. You\'ll save thousands instantly!',
        cpl_adv_joint: '🏠 <b>Joint Ownership:</b> Since your Home Loan interest is > ₹2L, make sure you are Joint Owners. Both of you can individually claim ₹2 Lakhs each (total ₹4L deduction) under Old Regime!',
        cpl_adv_80ca: '📉 <b>Partner A 80C:</b> Maximize ₹1.5L 80C if opting for Old Regime to save up to ₹46,800 a year.',
        cpl_adv_80cb: '📉 <b>Partner B 80C:</b> Maximize ₹1.5L 80C if opting for Old Regime to save up to ₹46,800 a year.',
        cpl_adv_hi: '🪪 <b>Health Insurance:</b> Don\'t buy two separate policies! Buy one Family Floater Plan. It is 20-30% cheaper and offers a shared larger sum assured.',
        cpl_adv_book: '📈 <b>Investment Booking:</b> Book the ₹{sip} SIPs in the name of {p} ({slab}% bracket). When you sell mutual funds later, Capital Gains logic is smoother, and dividend income will be taxed at the lower slab!',
        cpl_adv_split: '📈 <b>SIP Structure:</b> Split your ₹{sip} SIP exactly 50/50. This perfectly optimizes your ₹1 Lakh tax-free limit on Long Term Capital Gains (LTCG) for BOTH individuals every year (meaning ₹2 Lakhs tax-free gains per year!).',
        prt_a: 'Partner A', prt_b: 'Partner B', prt_eith: 'either partner', prt_both: 'both',
        tab_fire: '🔥 FIRE Planner', tab_life: '🎉 Life Events',
        fire_title: '<span class="gradient-text">FIRE</span> Planner', fire_desc: 'Financial Independence, Retire Early - Roadmap & Asset Shifts.',
        fire_lbl_age: 'Current Age', fire_lbl_retire: 'Target Retirement Age', fire_lbl_exp: 'Monthly Expenses Today (₹)', fire_lbl_port: 'Current Portfolio Total (₹)',
        fire_lbl_inv: 'Current Monthly SIP / Saving (₹)', fire_btn_run: 'Calculate FIRE Path 🔥', fire_res_title: '🔥 FIRE Roadmap', fire_res_plan: '🗺️ Month-by-Month Allocation Plan',
        life_title: '<span class="gradient-text">Life</span> Advisor', life_desc: 'AI strategy for big life events: Bonus, Marriage, Baby, Inheritance.',
        life_lbl_event: 'Select Life Event', life_opt_bonus: 'Large Cash Bonus / RSU', life_opt_inherit: 'Inheritance / Lump Sum', life_opt_marriage: 'Getting Married', life_opt_baby: 'New Baby Arrival',
        life_lbl_amt: 'Amount Involved (₹) (If applicable)', life_btn_run: 'Get AI Event Advice 🎉', life_res_title: '🧠 Event Financial Strategy',
        fire_verd: '💡 To retire by {retire} (in {years} yrs), your current expenses of ₹{exp} will inflate to ~₹{infExp} (at 6%). You need a FIRE Corpus of <b>₹{corpus}</b>. You currently have ₹{port}.',
        fire_adv_short: '⚠️ Your current ₹{sip} SIP is not enough to reach ₹{corpus} in {years} years. You need to increase it to ₹{reqSip}/month (assuming 12% return).',
        fire_adv_good: '✅ Great job! Your current ₹{sip} SIP is sufficient to hit ₹{corpus} comfortably in {years} years at 12% returns.',
        fire_adv_safe: '🛡️ Asset Shift: Move 3 years of expenses (₹{safe}) from Equity to Safe Debt Funds/FDs 3 years before retirement to avoid sequence-of-returns risk.',
        fire_adv_ins: '🏥 Pre-Retirement Health: Upgrade your base Health Insurance to a Super Top-Up model before 45, as premiums skyrocket post-50.',
        life_verd_bonus: '💼 <b>Bonus Allocation Rule:</b> Put 10% (₹{fun}) towards guilt-free spending! Use 30% (₹{tax}) to pre-pay high-interest loans (Personal/Credit Card), and inject the remaining 60% (₹{inv}) into your equity MF portfolio.',
        life_verd_inherit: '🏛️ <b>Inheritance Strategy:</b> Do not spend the ₹{amt} immediately. Park it in a Liquid Fund for 6 months while you grieve or plan. Then use STP (Systematic Transfer Plan) to move it slowly to an Index Fund over 12 months to average out market volatility.',
        life_verd_marriage: '💍 <b>Marriage Finances:</b> 1. Combine your finances honestly. 2. Upgrade to a Family Floater Health Insurance. 3. Nominate your spouse in all FDs, MFs, and EPF. 4. Draft a combined monthly budget using the 50/30/20 rule.',
        life_verd_baby: '🍼 <b>New Baby Planning:</b> 1. Buy a Term Insurance immediately (at least 15x annual income) to protect the child. 2. Start a Step-up SIP in a Flexicap Fund specifically for higher education (Target: 18 years compounding). 3. Add the newborn to your corporate/personal Health Insurance.',
        tab_rent: '🏠 Rent vs Buy',
        rent_title: '<span class="gradient-text">Real</span> Estate Simulator', rent_desc: 'AI mathematical breakdown: Should you buy a house or rent and invest the difference?',
        rent_lbl_cost: 'Property Cost (₹)', rent_lbl_dp: 'Down Payment (₹)', rent_lbl_roi: 'Home Loan Interest Rate (%)',
        rent_lbl_tenure: 'Loan Tenure (Years)', rent_lbl_rent: 'Current Monthly Rent (₹)', rent_lbl_prop_app: 'Property Appreciation (% p.a.)',
        rent_lbl_mf_ret: 'Expected MF Return (% p.a.)', rent_btn_run: 'Simulate Future Scenarios 🔮',
        rent_res_title: '🏢 Buy vs Rent Net Worth',
        rent_verd_buy: '💡 <b>Buying Wins!</b> After {years} years, buying creates a Net Worth of <b>₹{buyNw}</b> vs Renting\'s <b>₹{rentNw}</b>. The property appreciation and loan leverage worked in your favor.',
        rent_verd_rent: '💡 <b>Renting Wins!</b> After {years} years, renting and investing creates a Net Worth of <b>₹{rentNw}</b> vs Buying\'s <b>₹{buyNw}</b>. Your Mutual Fund compounding heavily outperformed property appreciation rates.',
        rent_adv_emi: '🏦 <b>EMI Breakdown:</b> Your estimated EMI is ₹{emi}. Rent is currently ₹{rent}. The difference of ₹{diff} will be invested into equity every month.',
        rent_adv_tax: '⚖️ <b>Tax Tip:</b> Buying gives you Section 24(b) (₹2L interest exemption) and 80C (₹1.5L principal) deductions, making the hidden cost of EMI slightly lower.',
        rent_adv_flex: '🚶‍♂️ <b>Flexibility:</b> Renting offers high job mobility and zero property tax/maintenance (which costs ~1% of property value annually).',
        tab_debt: '💳 Debt Eraser',
        debt_title: '<span class="gradient-text">Debt</span> Eraser', debt_desc: 'AI optimizes your loan EMIs to get you out of debt months or years earlier.',
        debt_lbl_l1_bal: 'Loan 1: Outstanding Balance (₹)', debt_lbl_l1_roi: 'Loan 1: Interest Rate (%)', debt_lbl_l1_emi: 'Loan 1: Current EMI (₹)',
        debt_lbl_l2_bal: 'Loan 2: Outstanding Balance (₹)', debt_lbl_l2_roi: 'Loan 2: Interest Rate (%)', debt_lbl_l2_emi: 'Loan 2: Current EMI (₹)',
        debt_lbl_extra: 'Extra Monthly Payment You Can Make (₹)', debt_btn_run: 'Find the Fastest Payoff Path ⚡',
        debt_res_title: '💳 AI Debt Optimization Strategy',
        debt_verd_time_saved: '💡 By adding ₹{extra} monthly using the <b>Avalanche Method</b>, you will be completely debt-free in <b>{newMonths} months</b> instead of {oldMonths} months! (Saved {diffMonths} months).',
        debt_verd_int_saved: '💡 Total Interest Paid drops from ₹{oldInt} to <b>₹{newInt}</b>. That is a guaranteed savings of <b>₹{diffInt}</b>!',
        debt_adv_avalanche: '📈 <b>Avalanche Strategy:</b> Always pay the minimum on both loans. Direct all extra cash toward the loan with the highest interest rate. Once paid off, roll that entire EMI onto the next loan.',
        debt_adv_warning: '⚠️ <b>Financial Danger:</b> If your loan interest rate is above 12%, mathematically you should generally stop discretionary investments and aggressively pay down the debt first.',
        tab_gold: '🥇 Gold Analyzer',
        gold_title: '<span class="gradient-text">Gold</span> Analyzer', gold_desc: 'Calculate the hidden losses of Physical Gold vs Sovereign Gold Bonds (SGB).',
        gold_lbl_port: 'Total Net Worth / Portfolio (₹)', gold_lbl_phys: 'Physical Gold Value (Jewelry/Coins) (₹)', gold_lbl_sgb: 'SGB / Gold ETF Value (₹)',
        gold_btn_run: 'Analyze Gold Portfolio 🔎', gold_res_title: '🥇 AI Gold Strategy',
        gold_verd_alloc_good: '✅ <b>Perfect Allocation:</b> Your total gold is {pct}% of your portfolio, well within the 10-15% maximum limit for a healthy portfolio.',
        gold_verd_alloc_bad: '⚠️ <b>Overweight Warning:</b> Your gold is {pct}% of your portfolio. Gold is an inflation hedge, not a compounding growth asset. Keep it under 15%.',
        gold_verd_loss: '💡 Over 8 years, holding ₹{amount} in Physical Gold instead of SGB causes a hidden loss of ~<b>₹{loss}</b>! This is due to 0% interest, 10% making charges lost on sale, and LTCG tax.',
        gold_verd_sgb: '💡 Since you hold SGB, you will earn ₹{interest} as extra risk-free interest over 8 years, completely tax-free on maturity!',
        gold_adv_sgb: '📈 <b>SGB Rule:</b> If buying for investment, never buy physical gold. Buy Sovereign Gold Bonds (SGBs) from the RBI for an extra 2.5% annual interest and zero Capital Gains Tax.',
        gold_adv_limit: '🚫 <b>Diversification:</b> Do not treat gold jewelry as an investment for your retirement. It is an emotional expense. Shift heavily into Equity Mutual Funds for real wealth creation.'
    },
    hi: {
        app_title: '<span class="gradient-text">मनी हेल्थ</span> मेंटर', app_desc: 'अपना एआई-पावर्ड फाइनेंशियल स्कोर और पर्सनैलाइज्ड एक्शन प्लान प्राप्त करें।',
        form_title: '📊 अपनी आर्थिक जानकारी दें', lbl_age: 'उम्र (Age)', lbl_income: 'मासिक आय (₹)', lbl_expenses: 'मासिक खर्च (₹)', lbl_emergency: 'इमरजेंसी फंड (कितने महीने का है)',
        lbl_health_ins: 'क्या आपके पास हेल्थ इंश्योरेंस है?', lbl_life_ins: 'क्या आपके पास जीवन बीमा (Term Plan) है?', lbl_investments: 'आपने कहाँ निवेश किया है?', lbl_tax: 'टैक्स सेविंग (80C)',
        lbl_debt: 'क्या आपके ऊपर कोई कर्ज (Loan) है?', lbl_emi: 'ईएमआई (EMI) आपकी आय का कितना % है?', btn_analyze: 'मेरा फाइनेंस एनालाइज करें 🚀', btn_recalc: 'दोबारा कैलकुलेट करें 🔄',
        status_analyzing: 'एनालाइज कर रहा है...', status_good: 'EXCELLENT', status_average: 'AVERAGE', status_poor: 'POOR',
        res_summary: '📌 सारांश (Summary)', res_problems: '⚠️ मुख्य समस्याएं', res_action: '✅ एक्शन प्लान', res_invest: '📈 मासिक निवेश सुझाव', res_emergency: '🛡️ इमरजेंसी फंड सलाह', res_tip: '💡 स्मार्ट टिप',
        opt_yes_personal: 'हाँ (पर्सनल लिया है)', opt_no_corp: 'नहीं (या सिर्फ कंपनी का है)', opt_yes: 'हाँ', opt_no: 'नहीं',
        opt_inv_none: 'कहीं नहीं / सिर्फ सेविंग अकाउंट में', opt_inv_fd: 'FD और PPF में', opt_inv_mf: 'म्यूचुअल फंड और SIP में', opt_inv_stocks: 'शेयर बाजार (Stocks) में',
        opt_tax_yes: 'हाँ (पूरी ₹1.5L की लिमिट)', opt_tax_no: 'नहीं / पूरी तरह से इस्तेमाल नहीं',
        
        rep_sum_good: "आपकी आमदनी और बचत दर बहुत मजबूत है! आप वेल्थ बनाने की सही राह पर हैं। थोड़ी सी ट्यूनिंग के साथ यह एकदम परफेक्ट हो जाएगा।",
        rep_sum_avg: "आपकी आमदनी और बचत अच्छी है, लेकिन लॉन्ग-टर्म सुरक्षा (बीमा या इमरजेंसी फंड) और निवेश में प्लानिंग की कमी है। कुछ कदम उठाकर आप आराम से 'Good' ज़ोन में आ जाएंगे।",
        rep_sum_poor: "आपकी मौजूदा आर्थिक आदतें लगातार रिस्क पैदा कर रही हैं। अपनी आय और खर्चे को बैलेंस करके तुरंत सुरक्षा लेने का यही सही वक्त है।",
        rep_sum_alert: "अलर्ट! आपके खर्चे आपकी आमदनी से ज्यादा हैं। अपने लगातार बढ़ते खर्चों को रोकना आपका सबसे जरूरी काम है।",
        rep_prob_health: "पर्सनल हेल्थ इंश्योरेंस का न होना एक बड़ी मेडिकल इमरजेंसी में आपकी सारी बचत को जीरो कर सकता है।",
        rep_prob_life: "टर्म लाइफ इंश्योरेंस का न होना एक बड़ा जोखिम है, खास तौर पर अगर आपका परिवार आपकी आमदनी पर निर्भर है।",
        rep_prob_em: "सिर्फ {m} महीने का इमरजेंसी फंड अचानक नौकरी जाने या संकट के समय सपोर्ट नहीं करेगा।",
        rep_prob_inv: "पैसे सिर्फ बैंक अकाउंट या FD में रखने का मतलब है कि महंगाई आपकी बचत की वैल्यू कम कर रही है।",
        rep_prob_emi: "आपकी आमदनी का एक बहुत बड़ा हिस्सा ({p}%) ईएमआई चुकाने में खत्म हो जाता है।",
        rep_prob_none: "फिलहाल कोई बड़ा खतरा नहीं है! बस महँगाई को बीट करने के लिए रिटर्न्स पर फोकस रखें।",
        rep_act_health: "बैकअप के रूप में जल्द से जल्द अपने और परिवार के लिए कम से कम ₹5L से ₹10L का एक बेस हेल्थ इंश्योरेंस लें।",
        rep_act_life: "अगला कदम—एक प्योर टर्म लाइफ इंश्योरेंस लें (कवर आपकी सालाना आय का 10x से 15x होना चाहिए)।",
        rep_act_em: "अपने इमरजेंसी फंड को लगातार बचाएं जब तक यह पूरे 6 महीने के खर्चे (₹{amt}) तक न पहुँच जाए, और इसे लिक्विड म्यूचुअल फंड में रखें।",
        rep_act_emi: "महीने के कैशफ्लो को ठीक करने के लिए एक्स्ट्रा पेमेंट करके पर्सनल लोन या क्रेडिट कार्ड के बिल को परमानेंटली खत्म करने की कोशिश करें।",
        rep_act_inv: "सिर्फ फिक्स्ड रिटर्न वाली जगहों के बजाय थोड़ा पैसा SIP के जरिए इक्विटी म्यूचुअल फंड्स में लगाना शुरू करें!",
        rep_act_none: "अपने पोर्टफोलियो की कंपाउंडिंग का आनंद लें और हर साल आय बढ़ने के साथ SIP को 10% बढ़ाते रहें।",
        rep_inv_debt: "फिलहाल निवेश शुरू करने से पहले जरूरी है कि क्रेडिट कार्ड या भारी ब्याज वाले पर्सनल लोन का उधार खत्म किया जाए।",
        rep_inv_good: "आपके लिए सुझाया गया प्लान: ₹{sip} की मंथली SIP लगाएं — ₹{n50} सुरक्षित Nifty 50 Index Fund में, ₹{flexi} Flexi Cap Fund में और बाकी ₹{small} Small/Mid cap fund में।",
        rep_inv_basic: "आप अपने बजट से लगभग ₹{sav} बचा सकते हैं। कम से कम ₹{amt} की SIP एक लो-कॉस्ट Index Fund में शुरू करें।",
        rep_em_adv: "स्मार्ट रूल कहता है कि आपको अपने मासिक खर्चों (₹{exp}) को कम से कम 6 गुणा करके सुरक्षित रखना चाहिए। टारगेट: ₹{tgt}।",
        rep_tip: "कंपाउंडिंग का जादू: अगर आप इस ₹{sip} प्रति माह को बिना छोड़े म्यूचुअल फंड में अगले 15 साल डालते रहते हैं, तो आपके पास ₹{val} या उससे ज्यादा का बड़ा कॉर्पस तैयार हो सकता है!",
        
        tab_health: '📊 हेल्थ स्कोर', tab_tax: '⚖️ टैक्स विज़ार्ड', tab_couple: '👩‍❤️‍👨 कपल प्लानर',
        tax_title: '<span class="gradient-text">टैक्स</span> विज़ार्ड', tax_desc: 'AI पुरानी और नई टैक्स रिजीम (FY24-25) की तुलना करके आपकी बची हुई छूट ढूँढता है।',
        tax_upload_text: '📄 फॉर्म 16 / सैलरी स्लिप अपलोड करें', tax_upload_sub: '(AI विज़न सिमुलेशन)', tax_divider: 'या यहाँ खुद जानकारी भरें',
        tax_lbl_gross: 'कुल सालाना सैलरी (₹)', tax_lbl_hra: 'HRA छूट क्लेम (₹)', tax_lbl_80c: '80C छूट (ELSS, PF) (₹)',
        tax_lbl_80d: 'हेल्थ इंश्योरेंस प्रीमियम (80D) (₹)', tax_lbl_hl: 'होम लोन का ब्याज (₹)', tax_lbl_nps: 'NPS अतिरिक्त (80CCD(1B)) (₹)',
        tax_lbl_oth: 'LTA / अन्य छूट (₹)', tax_btn_run: 'FinAI टैक्स मॉडल रन करें ⚡', tax_res_new: 'नई टैक्स रिजीम (New Tax Regime)', tax_res_old: 'पुरानी टैक्स रिजीम (Old Tax Regime)',
        tax_res_new_sub: '(फ्लैट डिडक्शन के साथ)', tax_res_old_sub: '(सभी छूट क्लेम करने के बाद)', tax_res_verdict: '🏆 FinAI का फैसला', tax_res_advice: '💡 टैक्स बचाने की AI सलाह',
        tax_sim_ext: '🔄 AI से डेटा निकाला जा रहा है...', tax_sim_succ: '✅ डेटा सफलतापूर्वक एक्सट्रैक्ट हो गया',
        tax_verd_old: '💡 आपके लिए <b>पुरानी टैक्स रिजीम</b> बेहतर है। आपकी ज़्यादा टैक्स छूट की वजह से आप नई रिजीम के मुकाबले ₹{diff} बचा सकते हैं।',
        tax_verd_new: '💡 आपके लिए <b>नई टैक्स रिजीम</b> बेहतर है। आप इसमें ₹{diff} बचाएंगे। आपकी मौजूदा डिडक्शन फ्लैट रेट्स को मात देने के लिए काफी नहीं हैं।',
        tax_verd_same: '💡 दोनों रिजीम में आपका टैक्स बिल्कुल बराबर आ रहा है। आप नई रिजीम चुन सकते हैं (कम कागज़ी कारवाई)!',
        tax_adv_80c: '💰 ELSS/PF (80C) में ₹{diff} और इन्वेस्ट करें ताकि ₹1.5L की पूरी टैक्स छूट मिल सके।',
        tax_adv_nps: '🏦 अपना एक NPS Tier-1 अकाउंट खोलें। इसमें ₹50,000 इन्वेस्ट करने पर 80CCD(1B) के तहत एक्स्ट्रा ছাড় मिलती है (लगभग ₹15,600 की बचत)।',
        tax_adv_80d: '🏥 एक अच्छा हेल्थ इंश्योरेंस लें। आप 80D के तहत ₹25,000 तक क्लेम कर सकते हैं।',
        tax_adv_hra: '🏠 अगर आप किराये पर रहते हैं, तो अपनी HRA छूट बढ़ाने के लिए सही रेंट एग्रीमेंट जमा करें।',
        tax_adv_opt: '✨ आपने अपने टैक्स को पूरी तरह से ऑप्टिमाइज़ कर लिया है! कोई और डिडक्शन बाकी नहीं है।',
        cpl_title: '<span class="gradient-text">यूनिफाइड</span> प्लानर', cpl_desc: 'भारत का पहला AI जॉइंट फाइनेंशियल प्लानर जो दो आमदनियों को समझकर वेल्थ बचाता है।',
        cpl_partner_a: '👩‍💼 पार्टनर A', cpl_partner_b: '👨‍💼 पार्टनर B', cpl_lbl_income: 'सालाना आमदनी (₹)', cpl_lbl_80c: 'क्या 80C पूरा (₹1.5L) भर दिया है?',
        cpl_lbl_hl: 'होम लोन की EMI का बोझ (सालाना) (₹)', cpl_lbl_sip: 'हर महीने कुल जॉइंट SIP (₹)', cpl_btn_run: 'एकसाथ वेल्थ ऑप्टिमाइज़ करें 💍',
        cpl_res_title: '✅ यूनिफाइड FinAI ऑप्टिमाइज़ेशन स्ट्रेटेजी',
        cpl_adv_arb: '🏠 <b>टैक्स आर्बिट्रेज (Tax Arbitrage):</b> {p} उच्च टैक्स ब्रैकेट ({slab}%) में है। ध्यान रखें कि आधा-आधा बांटने के बजाय {p} अधिक से अधिक होम लोन का ब्याज छांट (छूट) ले। आप तुंरत हज़ारों बचाएंगे!',
        cpl_adv_joint: '🏠 <b>जॉइंट ओनरशिप:</b> क्योंकि आपके होम लोन का ब्याज ₹2L से अधिक है, इसलिए ध्यान रखें कि आप जॉइंट ओनर हैं। पुरानी रिजिम में दोनों अलग-अलग ₹2 लाख (कुल ₹4 लाख) का क्लेम कर सकते हैं!',
        cpl_adv_80ca: '📉 <b>पार्टनर A 80C:</b> अगर पुरानी रिजिम चुनते हैं तो साल में ₹46,800 तक बचाने के लिए 80C (₹1.5L) को पूरा करें।',
        cpl_adv_80cb: '📉 <b>पार्टनर B 80C:</b> अगर पुरानी रिजिम चुनते हैं तो साल में ₹46,800 तक बचाने के लिए 80C (₹1.5L) को पूरा करें।',
        cpl_adv_hi: '🪪 <b>हेल्थ इंश्योरेंस:</b> दो अलग-अलग पॉलिसियां न खरीदें! एक फैमिली फ्लोटर प्लान लें। यह 20-30% सस्ता होता है और एक शेयर किया गया बड़ा कवर देता है।',
        cpl_adv_book: '📈 <b>इन्वेस्टमेंट बुकिंग:</b> अपनी ₹{sip} की SIPs को {p} ({slab}% ब्रैकेट) के नाम पर बुक करें। बाद में म्यूचुअल फंड बेचते समय कैपिटल गेन्स टैक्स कम लगेगा!',
        cpl_adv_split: '📈 <b>SIP स्ट्रक्चर:</b> अपनी ₹{sip} SIP को बिल्कुल 50/50 में बांटें। यह आप दोनों के लिए लॉन्ग टर्म कैपिटल गेन्स (LTCG) पर ₹1 लाख की टैक्स-फ्री लिमिट को ऑप्टिमाइज़ करता है (यानी साल में ₹2 लाख टैक्स-फ्री मुनाफा!)।',
        prt_a: 'पार्टनर A', prt_b: 'पार्टनर B', prt_eith: 'कोई एक पार्टनर', prt_both: 'दोनों',
        tab_fire: '🔥 FIRE प्लानर', tab_life: '🎉 लाइफ इवेंट्स',
        fire_title: '<span class="gradient-text">FIRE</span> प्लानर', fire_desc: 'जल्दी रिटायर होने (FIRE) का पूरा रोडमैप और निवेश प्लान।',
        fire_lbl_age: 'वर्तमान उम्र', fire_lbl_retire: 'रिटायरमेंट उम्र (टारगेट)', fire_lbl_exp: 'वर्तमान मासिक खर्चा (₹)', fire_lbl_port: 'वर्तमान कुल निवेश (₹)',
        fire_lbl_inv: 'वर्तमान मासिक SIP (₹)', fire_btn_run: 'FIRE रोडमैप बनाएँ 🔥', fire_res_title: '🔥 FIRE रोडमैप', fire_res_plan: '🗺️ एलोकेशन प्लान',
        life_title: '<span class="gradient-text">लाइफ</span> एडवाइज़र', life_desc: 'बोनस, शादी, बच्चा, आदि बड़े इवेंट्स के लिए AI रणनीति।',
        life_lbl_event: 'लाइफ इवेंट चुनें', life_opt_bonus: 'बड़ा कैश बोनस', life_opt_inherit: 'इनहेरिटेंस / एकमुश्त रकम', life_opt_marriage: 'शादी', life_opt_baby: 'नए बच्चे का जन्म',
        life_lbl_amt: 'बोनस/रकम (₹) (यदि हो)', life_btn_run: 'AI इवेंट सलाह लें 🎉', life_res_title: '🧠 इवेंट फाइनेंशियल रणनीति',
        fire_verd: '💡 {retire} तक रिटायर होने के लिए ({years} साल), आपका ₹{exp} का खर्चा 6% महंगाई दर से ~₹{infExp} हो जाएगा। आपको <b>₹{corpus}</b> के FIRE कॉर्पस की जरूरत है। अभी आपके पास ₹{port} हैं।',
        fire_adv_short: '⚠️ आपकी वर्तमान ₹{sip} SIP {years} सालों में ₹{corpus} तक पहुँचने के लिए काफी नहीं है। इसे बढ़ाकर ₹{reqSip}/माह करना होगा (12% रिटर्न मानकर)।',
        fire_adv_good: '✅ बहुत बढ़िया! आपकी ₹{sip} SIP 12% रिटर्न पर {years} सालों में ₹{corpus} का लक्ष्य आराम से पूरा कर लेगी।',
        fire_adv_safe: '🛡️ एसेट शिफ्ट: रिटायरमेंट से 3 साल पहले अपने 3 साल के खर्चे (₹{safe}) को इक्विटी से निकालकर सुरक्षित FD/Debt फंड्स में डालें, ताकि मार्केट क्रैश से बचा जा सके।',
        fire_adv_ins: '🏥 रिटायरमेंट से पहले 45 की उम्र में अपने हेल्थ इंश्योरेंस को सुपर टॉप-अप मॉडल में अपग्रेड करें, क्योंकि 50 के बाद प्रीमियम बहुत बढ़ जाता है।',
        life_verd_bonus: '💼 <b>बोनस एलोकेशन नियम:</b> 10% (₹{fun}) मज़े के लिए खर्च करें! 30% (₹{tax}) से भारी ब्याज वाले लोन चुकाएं, और बचे हुए 60% (₹{inv}) को अपनी इक्विटी MF पोर्टफोलियो में डालें।',
        life_verd_inherit: '🏛️ <b>इनहेरिटेंस रणनीति:</b> इस ₹{amt} को तुरंत खर्च न करें। इसे 6 महीने Liquid Fund में रखें। फिर 12 महीनों के दौरान STP (Systematic Transfer Plan) के जरिए इंडेक्स फंड में लगाएं ताकि मार्केट के उतार-चढ़ाव का खतरा कम हो।',
        life_verd_marriage: '💍 <b>शादी का वित्त:</b> 1. अपने वित्त को ईमानदारी से मिलाएँ। 2. एक फैमिली फ्लोटर हेल्थ इंश्योरेंस लें। 3. सभी FD, MF और EPF में जीवनसाथी को नॉमिनी बनाएँ। 4. 50/30/20 नियम का पालन करते हुए एक साझा मासिक बजट बनाएँ।',
        life_verd_baby: '🍼 <b>नए बच्चे की प्लानिंग:</b> 1. बच्चे की सुरक्षा के लिए तुरंत एक टर्म इंश्योरेंस लें (आय का 15x)। 2. उच्च शिक्षा के लिए फ्लेक्सीकैप फंड में स्टेप-अप SIP शुरू करें (टारगेट 18 साल)। 3. बच्चे को तुरंत हेल्थ इंश्योरेंस में जोड़ें।',
        tab_rent: '🏠 रेंट vs बाय',
        rent_title: '<span class="gradient-text">रियल</span> एस्टेट सिमुलेटर', rent_desc: 'AI का गणितीय विश्लेषण: क्या आपको घर खरीदना चाहिए या किराए पर रहकर बचे पैसे निवेश करने चाहिए?',
        rent_lbl_cost: 'प्रॉपर्टी की कीमत (₹)', rent_lbl_dp: 'डाउन पेमेंट (₹)', rent_lbl_roi: 'होम लोन ब्याज दर (%)',
        rent_lbl_tenure: 'लोन की अवधि (साल)', rent_lbl_rent: 'वर्तमान मासिक किराया (₹)', rent_lbl_prop_app: 'प्रॉपर्टी रेट में हर साल बढ़त (%)',
        rent_lbl_mf_ret: 'म्यूचुअल फंड से उम्मीद (% सालाना)', rent_btn_run: 'भविष्य का विश्लेषण करें 🔮',
        rent_res_title: '🏢 घर खरीदना vs किराए पर रहना (Net Worth)',
        rent_verd_buy: '💡 <b>घर खरीदना बेहतर है!</b> {years} साल बाद, घर खरीदने से आपकी नेट वर्थ <b>₹{buyNw}</b> होगी, जबकि किराए पर <b>₹{rentNw}</b> होगी। प्रॉपर्टी के रेट बढ़ने से आपको फायदा हुआ।',
        rent_verd_rent: '💡 <b>किराए पर रहना बेहतर है!</b> {years} साल बाद, किराए पर रहकर SIP करने से आपकी नेट वर्थ <b>₹{rentNw}</b> होगी, जबकि घर खरीदने पर <b>₹{buyNw}</b> होगी। म्यूचुअल फंड की कंपाउंडिंग जीत गई।',
        rent_adv_emi: '🏦 <b>EMI ब्रेकडाउन:</b> आपकी अनुमानित EMI ₹{emi} है। अभी किराया ₹{rent} है। हर महीने बचे हुए ₹{diff} को म्यूचुअल फंड में डाला जाएगा।',
        rent_adv_tax: '⚖️ <b>टैक्स टिप:</b> घर खरीदने पर सेक्शन 24(b) (₹2L ब्याज) और 80C (₹1.5L मूलधन) की छूट मिलती है, जिससे EMI का असली बोझ थोड़ा कम हो जाता है।',
        rent_adv_flex: '🚶‍♂️ <b>आजादी (Flexibility):</b> किराए पर रहने से आप कभी भी नौकरी बदलने के लिए शहर छोड़ सकते हैं, और कोई मेंटेनेंस / प्रॉपर्टी टैक्स (सालाना 1%) भी नहीं देना पड़ता।',
        tab_debt: '💳 डेब्ट इरेज़र (कर्ज मुक्ति)',
        debt_title: '<span class="gradient-text">डेब्ट</span> इरेज़र', debt_desc: 'AI आपके EMI को ऑप्टिमाइज़ करके आपको महीनों या सालों पहले कर्ज मुक्त बना देगा।',
        debt_lbl_l1_bal: 'लोन 1: बचा हुआ बैलेंस (₹)', debt_lbl_l1_roi: 'लोन 1: ब्याज दर (%)', debt_lbl_l1_emi: 'लोन 1: वर्तमान EMI (₹)',
        debt_lbl_l2_bal: 'लोन 2: बचा हुआ बैलेंस (₹)', debt_lbl_l2_roi: 'लोन 2: ब्याज दर (%)', debt_lbl_l2_emi: 'लोन 2: वर्तमान EMI (₹)',
        debt_lbl_extra: 'अतिरिक्त मासिक भुगतान जो आप कर सकते हैं (₹)', debt_btn_run: 'कर्ज मुक्ति का सबसे तेज़ रास्ता खोजें ⚡',
        debt_res_title: '💳 AI लोन ऑप्टिमाइज़ेशन रणनीति',
        debt_verd_time_saved: '💡 हर महीने ₹{extra} ज़्यादा देकर और <b>Avalanche तरीका</b> अपनाकर, आप {oldMonths} की बजाय सिर्फ <b>{newMonths} महीनों</b> में कर्ज मुक्त हो जाएंगे! (पूरे {diffMonths} महीने बचाए)।',
        debt_verd_int_saved: '💡 कुल ब्याज का खर्च ₹{oldInt} से गिरकर <b>₹{newInt}</b> हो जाएगा। यानी <b>₹{diffInt}</b> की पक्की बचत!',
        debt_adv_avalanche: '📈 <b>एवलॉन्च रणनीति:</b> दोनों लोन्स की न्यूनतम EMI भरें। बचा हुआ सारा अतिरिक्त पैसा उस लोन में डालें जिसका ब्याज दर (Interest Rate) सबसे ज्यादा है। एक लोन खत्म होने पर उसकी EMI दूसरे में जोड़ दें।',
        debt_adv_warning: '⚠️ <b>खतरा (Warning):</b> अगर आपके लोन की ब्याज दर 12% से अधिक है, तो पहले लोन चुकाने पर पूरा जोर देना चाहिए।',
        tab_gold: '🥇 गोल्ड (SGB) एनालाइजर',
        gold_title: '<span class="gradient-text">गोल्ड</span> एनालाइजर', gold_desc: 'फिजिकल गोल्ड (गहने) vs SGB के बीच छिपे हुए नुकसान और फायदे का गणित समझें।',
        gold_lbl_port: 'आपकी कुल जमा-पूंजी (Net Worth) (₹)', gold_lbl_phys: 'फिजिकल गोल्ड की कीमत (गहने/सिक्के) (₹)', gold_lbl_sgb: 'SGB / डिजिटल गोल्ड की कीमत (₹)',
        gold_btn_run: 'गोल्ड का विश्लेषण करें 🔎', gold_res_title: '🥇 AI गोल्ड रणनीति',
        gold_verd_alloc_good: '✅ <b>सही एलोकेशन:</b> आपका कुल गोल्ड आपकी पूंजी का {pct}% है, जो 10-15% की सुरक्षित सीमा के अंदर है।',
        gold_verd_alloc_bad: '⚠️ <b>चेतावनी:</b> आपका गोल्ड आपकी पूंजी का {pct}% है! गोल्ड सिर्फ बचाव के लिए होता है, वेल्थ बनाने के लिए नहीं। इसे 15% से कम रखें।',
        gold_verd_loss: '💡 8 सालों में, SGB की बजाय ₹{amount} का फिजिकल गोल्ड रखने से आपको लगभग <b>₹{loss}</b> का नुकसान होगा! (0% ब्याज, 10% मेकिंग चार्ज नुकसान, और टैक्स)।',
        gold_verd_sgb: '💡 आपके पास SGB है, इसलिए आपको 8 सालों में ₹{interest} का एक्स्ट्रा ब्याज मिलेगा, जो मैच्योरिटी पर पूरी तरह टैक्स-फ्री होगा!',
        gold_adv_sgb: '📈 <b>SGB नियम:</b> निवेश के लिए कभी भी फिजिकल गोल्ड न खरीदें। RBI से सॉवरेन गोल्ड बॉन्ड (SGB) खरीदें, ताकि 2.5% का एक्स्ट्रा ब्याज और टैक्स छूट मिल सके।',
        gold_adv_limit: '🚫 <b>डाइवर्सिफिकेशन:</b> रिटायरमेंट या निवेश के लिए गहनों पर निर्भर न रहें। यह एक खर्च है। असल वेल्थ के लिए म्यूचुअल फंड्स में निवेश बढ़ाएं।'
    },
    ta: {
        app_title: '<span class="gradient-text">Money Health</span> Mentor', app_desc: 'உங்கள் நிதியியல் மதிப்பெண் மற்றும் தனிப்பயனாக்கப்பட்ட திட்டத்தை அறிந்துகொள்ளுங்கள்.',
        form_title: '📊 உங்கள் நிதி விவரங்கள்', lbl_age: 'வயது (Age)', lbl_income: 'மாதாந்திர வருமானம் (₹)', lbl_expenses: 'மாதாந்திர செலவுகள் (₹)', lbl_emergency: 'அவசர நிதி (எத்தனை மாதச் செலவு)',
        lbl_health_ins: 'உடல்நல காப்பீடு உள்ளதா?', lbl_life_ins: 'ஆயுள் காப்பீடு (Term Plan) உள்ளதா?', lbl_investments: 'முதலீடுகள் (Investments)?', lbl_tax: 'வரி சேமிப்பு (80C)',
        lbl_debt: 'கடன்கள் / லோன் உள்ளதா?', lbl_emi: 'உங்கள் வருமானத்தில் EMI சதவீதம் %', btn_analyze: 'எனது நிதியை ஆலோசி 🚀', btn_recalc: 'மீண்டும் கணக்கிடு 🔄',
        status_analyzing: 'ஆய்வு செய்கிறது...', status_good: 'மிக நன்று', status_average: 'நடுத்தரம்', status_poor: 'மோசம்',
        res_summary: '📌 சுருக்கம்', res_problems: '⚠️ முக்கியப் பிரச்சனைகள்', res_action: '✅ செயல் திட்டம்', res_invest: '📈 மாதாந்திர முதலீட்டு ஆலோசனை', res_emergency: '🛡️ அவசர நிதி ஆலோசனை', res_tip: '💡 ஸ்மார்ட் டிப்',
        opt_yes_personal: 'ஆம் (தனிப்பட்ட)', opt_no_corp: 'இல்லை (நிறுவனத்தின் காப்பீடு)', opt_yes: 'ஆம்', opt_no: 'இல்லை',
        opt_inv_none: 'எதுவும் இல்லை / சேமிப்பு', opt_inv_fd: 'FD மற்றும் PPF', opt_inv_mf: 'மியூச்சுவல் ஃபண்ட்ஸ் (SIP)', opt_inv_stocks: 'பங்குச்சந்தை (Stocks)',
        opt_tax_yes: 'ஆம் (₹1.5L வரை)', opt_tax_no: 'இல்லை / குறைவாக',
        rep_sum_good: "உங்கள் வருமானம் மற்றும் சேமிப்பு மிகவும் வலுவாக உள்ளது! நீங்கள் செல்வத்தை உருவாக்கும் சரியான பாதையில் உள்ளீர்கள்.",
        rep_sum_avg: "உங்கள் வருமானமும் சேமிப்பும் நன்றாக உள்ளது, ஆனால் காப்பீடு மற்றும் முதலீடுகளில் முறையான திட்டமிடல் இல்லை. சில நடவடிக்கைகளை எடுத்தால் நீங்கள் 'Good' நிலைக்கு மாறலாம்.",
        rep_sum_poor: "உங்கள் தற்போதைய நிதியியல் பழக்கவழக்கங்கள் அபாயத்தை உருவாக்குகின்றன. உங்களின் பாதுகாப்புகளை (காப்பீடு / ஃபண்ட்) தொடங்க இதுவே சரியான நேரமாகும்.",
        rep_sum_alert: "எச்சரிக்கை! உங்கள் செலவுகள் உங்கள் வருமானத்தை விட அதிகமாக உள்ளன. தேவையற்ற செலவுகளைக் குறைப்பது மிக முக்கிய பணியாகும்.",
        rep_prob_health: "உடல்நலக் காப்பீடு இல்லாதது, ஒரு பெரிய மருத்துவ அவசரத்தின் போது உங்கள் அனைத்து சேமிப்புகளையும் காலி செய்துவிடும்.",
        rep_prob_life: "டேர்ம் ஆயுள் காப்பீடு இல்லாதது பெரும் ஆபத்தாகும், குறிப்பாக உங்கள் குடும்பம் உங்கள் வருமானத்தைச் சார்ந்திருந்தால்.",
        rep_prob_em: "வெறும் {m} மாதங்களுக்கான அவசர நிதி இருப்பது, எதிர்பாராத வேலை இழப்பின் போது போதுமானதாக இருக்காது.",
        rep_prob_inv: "வங்கிக் கணக்கு அல்லது FD-களில் மட்டுமே பணத்தை வைப்பது பணவீக்கம் உங்கள் சேமிப்பின் மதிப்பை அழித்துவிடும் எனபதைக் குறிக்கிறது.",
        rep_prob_emi: "உங்கள் வருமானத்தின் ஒரு பெரிய பகுதி ({p}%) கடன்களை அடைப்பதற்கே செலவாகிறது.",
        rep_prob_none: "தற்போது பெரிய அபாயங்கள் ஏதும் இல்லை! பணவீக்கத்தை முறியடிக்க அதிக லாபம் தரும் முதலீடுகளில் கவனம் செலுத்துங்கள்.",
        rep_act_health: "பாதுகாப்பிற்காக, குறைந்தது ₹5L முதல் ₹10L வரையிலான அடிப்படை சுகாதார காப்பீட்டை விரைவாகப் பெறுங்கள்.",
        rep_act_life: "அடுத்த படி—ஒரு சரியான டேர்ம் ஆயுள் காப்பீட்டைப் பெறுங்கள் (கவரேஜ் உங்கள் ஆண்டு வருமானத்தை விட 10x முதல் 15x வரை இருக்க வேண்டும்).",
        rep_act_em: "உங்கள் அவசர நிதி 6 மாதச் செலவுகளை (₹{amt}) அடையும் வரை தொடர்ந்து சேமித்து வாருங்கள்.",
        rep_act_emi: "தனிநபர் கடன்கள் அல்லது கிரெடிட் கார்டு பில்களை விரைவாக கட்டி முடிக்க முயற்சியுங்கள்.",
        rep_act_inv: "SIP மூலம் ஈக்விட்டி மியூச்சுவல் ஃபண்டுகளில் சிறிது பணத்தை முதலீடு செய்யத் தொடங்குங்கள்!",
        rep_act_none: "உங்கள் போர்ட்ஃபோலியோ பெருகியதை ரசியுங்கள். ஒவ்வொரு ஆண்டும் உங்கள் SIP-யினை 10% சந்தோஷமாக அதிகரிக்கலாம்.",
        rep_inv_debt: "அதிக வட்டி கொண்ட கடன்களை அடைத்து தேவையற்ற செலவுகளைக் குறைப்பது முதலீடுகளைத் தொடங்கும் முன் மிகவும் அவசியமாகும்.",
        rep_inv_good: "உங்களுக்கான திட்டம்: ₹{sip} மாதாந்திர SIP தொடங்குங்கள் — பாதுகாப்பான Nifty 50 Index Fund-ல் ₹{n50}, Flexi Cap Fund-ல் ₹{flexi} மற்றும் எஞ்சிய ₹{small} Small/Mid cap fund-ல் முதலீடு செய்யுங்கள்.",
        rep_inv_basic: "உங்கள் செலவுப்போகு உள்ள மீத பணத்தில் குறைந்தபட்சம் ₹{amt} ஒர் Index Fund-ல் தொடங்குங்கள். பழகிய பின் தொகையை அதிகரிக்கலாம்.",
        rep_em_adv: "ஒரு சிறந்த விதி என்னவென்றால், குறைந்தது 6 மாத செலவுகளை (₹{tgt}) நீங்கள் சேமித்து வைக்க வேண்டும். இதை Savings AC மற்றும் Liquid MFs என பிரித்து வையுங்கள்.",
        rep_tip: "கூட்டு வட்டியின் மேஜிக்: நீங்கள் அடுத்த 15 வருடங்களுக்கு இந்த ₹{sip} பணத்தை SIP-ல் (சுமார் 12% ரிட்டர்ன்) தவறாமல் முதலீடு செய்தால், எந்தவிதக் கடின உழைப்பும் இல்லாமல் நீங்க ₹{val}-க்கும் குறையாத சொத்து மதிப்பை பெறமுடியும்!",
        tab_health: '📊 சுகாதார மதிப்பெண்', tab_tax: '⚖️ வரி வழிகாட்டி', tab_couple: '👩‍❤️‍👨 ஜோடித் திட்டம்',
        tax_title: '<span class="gradient-text">வரி</span> வழிகாட்டி', tax_desc: 'பழைய வரி மற்றும் புதிய வரியை AI ஒப்பிட்டு உங்கள் வரிச் சேமிப்பைக் (FY24-25) கணக்கிடுகிறது.',
        tax_upload_text: '📄 படிவம் 16 (Form 16) / Salary Slip', tax_upload_sub: '(AI ஸ்கேன் சிமுலேஷன்)', tax_divider: 'அல்லது கீழே உள்ளிடவும்',
        tax_lbl_gross: 'மொத்த ஆண்டு சம்பளம் (₹)', tax_lbl_hra: 'HRA விலக்கு (₹)', tax_lbl_80c: '80C முதலீடுகள் (ELSS, PF) (₹)',
        tax_lbl_80d: 'உடல்நல காப்பீடு (80D) (₹)', tax_lbl_hl: ' வீட்டுக் கடன் வட்டி (₹)', tax_lbl_nps: 'NPS கூடுதல் (80CCD(1B)) (₹)',
        tax_lbl_oth: 'LTA / மற்ற விலக்குகள் (₹)', tax_btn_run: 'வரி மாதிரியை இயக்கு ⚡', tax_res_new: 'புதிய வரி முறை (New Tax)', tax_res_old: 'பழைய வரி முறை (Old Tax)',
        tax_res_new_sub: '(ஸ்டாண்டர்ட் டிடக்ஷன் உடன்)', tax_res_old_sub: '(விலக்குகள் சேர்த்தது)', tax_res_verdict: '🏆 AI தீர்ப்பு', tax_res_advice: '💡 AI வரிச் சேமிப்பு ஆலோசனை',
        tax_sim_ext: '🔄 AI விவரங்களை எடுக்கிறது...', tax_sim_succ: '✅ விவரங்கள் எடுக்கப்பட்டன',
        tax_verd_old: '💡 உங்களுக்கு <b>பழைய வரி முறை</b> சிறந்தது. நீங்கள் புதிய வரி முறையை விட ₹{diff} சேமிக்கிறீர்கள்.',
        tax_verd_new: '💡 உங்களுக்கு <b>புதிய வரி முறை</b> சிறந்தது. நீங்கள் இதுவே ₹{diff} சேமிக்கிறீர்கள்.',
        tax_verd_same: '💡 இரண்டிலும் வரி தொகை ஒன்றுதான். புதிய வரி முறையைத் தேர்ந்தெடுக்கவும்.',
        tax_adv_80c: '💰 ELSS / PF-ல் மேலும் ₹{diff} முதலீடு செய்து முழு ₹1.5L வரி விலக்கைப் பெறுங்கள்.',
        tax_adv_nps: '🏦 NPS Tier-1 கணக்கைத் திறக்கவும். ₹50,000 முதலீடு செய்தால் ₹15,600 வரி மிச்சமாகும்.',
        tax_adv_80d: '🏥 சிறந்த உடல்நலக் காப்பீடு வாங்கவும். நீங்கள் 80D கீழ் ₹25,000 வரை கோரலாம்.',
        tax_adv_hra: '🏠 வாடகை வீடானால், HRA விலக்கை அதிகரிக்க வீட்டு வாடகை ஒப்பந்தத்தை சமர்ப்பிக்கவும்.',
        tax_adv_opt: '✨ நீங்கள் உங்கள் வரிகளை முழுமையாக நிர்வகித்துவிட்டீர்கள்! இனி மிச்சம் தேவையற்றது.',
        cpl_title: '<span class="gradient-text">ஜோடி</span> திட்டம்', cpl_desc: 'உங்கள் இரண்டு வருமானங்களை ஒப்பிட்டு வரிச் சிக்கலைத் தீர்க்கும் AI திட்டம்.',
        cpl_partner_a: '👩‍💼 கூட்டாளி A', cpl_partner_b: '👨‍💼 கூட்டாளி B', cpl_lbl_income: 'ஆண்டு வருமானம் (₹)', cpl_lbl_80c: '80C முழுமை (₹1.5L) அடைத்ததா?',
        cpl_lbl_hl: 'வீட்டுக் கடன் EMI (ஆண்டில்) (₹)', cpl_lbl_sip: 'மாதாந்திர கூட்டுச் சேமிப்பு இலக்கு (₹)', cpl_btn_run: 'செல்வத்தை மேம்படுத்துங்கள் 💍',
        cpl_res_title: '✅ AI ஜோடி நிதிச் சலுகைகள்',
        cpl_adv_arb: '🏠 <b>Tax Arbitrage:</b> {p} அதிக வரிப் பிரிவில் ({slab}%) உள்ளார். எனவே வீட்டுக் கடன் வட்டி விலக்கை பாதிக்கு பாதி பிரிக்காமல், முழுமையாக {p} மட்டுமே செய்ய வேண்டும்!',
        cpl_adv_joint: '🏠 <b>ஜாயிண்ட் (Joint):</b> வீட்டுக் கடன் வட்டி ₹2L-க்கும் அதிகம் தால், நீங்கள் பழைய வரியில் இருவரும் தலா ₹2 லட்சம் (மொத்தம் ₹4L) கோரலாம்!',
        cpl_adv_80ca: '📉 <b>கூட்டாளி A 80C:</b> பழைய வரி முறை எனில், ஒரு ஆண்டிற்கு ₹46,800 வரை வரியைச் சேமிக்க ₹1.5L 80C முதலீடு செய்யுங்கள்.',
        cpl_adv_80cb: '📉 <b>கூட்டாளி B 80C:</b> பழைய வரி முறை எனில், ஒரு ஆண்டிற்கு ₹46,800 வரை வரியைச் சேமிக்க ₹1.5L 80C முதலீடு செய்யுங்கள்.',
        cpl_adv_hi: '🪪 <b>உடல்நலக் காப்பீடு:</b> இரண்டு தனித்தனியாக காப்பீடு எடுக்க வேண்டாம்! மலிவான Family Floater Plan எடுக்கவும்.',
        cpl_adv_book: '📈 <b>முதலீட்டு கட்டமைப்பு (Investment):</b> உங்களின் ₹{sip}-ஐ {p} ({slab}% bracket) பெயரில் SIP செய்யுங்கள்! எதிர்காலத்தில் வரி மிச்சமாகும்.',
        cpl_adv_split: '📈 <b>SIP Structure:</b> உங்கள் ₹{sip} SIP-ஐ சரி பாதியாகப் பிரிக்கவும். இதனால் லாபத்திற்கு ₹1 லட்சம் வரி இல்லாத வரம்பு (LTCG limit) இரண்டு பேருக்கும் கிடைக்கும்.',
        prt_a: 'கூட்டாளி A', prt_b: 'கூட்டாளி B', prt_eith: 'யாராவது ஒருவர்', prt_both: 'இருவரும்',
        tab_fire: '🔥 FIRE திட்டம்', tab_life: '🎉 முக்கிய நிகழ்வுகள்',
        fire_title: '<span class="gradient-text">FIRE</span> திட்டம்', fire_desc: 'விரைவாக ஓய்வு பெறுவதற்கான (FIRE) முழுமையான முதலீட்டுத் திட்டம்.',
        fire_lbl_age: 'தற்போதைய வயது', fire_lbl_retire: 'ஓய்வு வயது (இலக்கு)', fire_lbl_exp: 'தற்போதைய மாதச் செலவு (₹)', fire_lbl_port: 'தற்போதைய மொத்த முதலீடு (₹)',
        fire_lbl_inv: 'மாதாந்திர முதலீடு/SIP (₹)', fire_btn_run: 'FIRE திட்டத்தை உருவாக்கு 🔥', fire_res_title: '🔥 FIRE இலக்கு', fire_res_plan: '🗺️ முதலீட்டுத் திட்டம் விகீதம்',
        life_title: '<span class="gradient-text">நிகழ்வு</span> வழிகாட்டி', life_desc: 'போனஸ், திருமணம் மற்றும் குழந்தை பிறப்புக்கான AI வழிகாட்டி.',
        life_lbl_event: 'நிகழ்வைத் தேர்ந்தெடுக்கவும்', life_opt_bonus: 'பெரிய போனஸ் / RSU', life_opt_inherit: 'மொத்த பணம் (சுதந்தரம்)', life_opt_marriage: 'திருமணம்', life_opt_baby: 'குழந்தை பிறப்பு',
        life_lbl_amt: 'பணத்தின் அளவு (₹) (இருப்பின்)', life_btn_run: 'AI ஆலோசனையைப் பெறு 🎉', life_res_title: '🧠 நிகழ்வு நிதி வியூகம்',
        fire_verd: '💡 {retire} வயதில் ஓய்வு பெற (இன்னும் {years} ஆண்டுகள்), உங்கள் தற்போதைய செலவு ₹{exp} பணவீக்கத்தால் ~₹{infExp} ஆக உயரும். உங்களுக்கு <b>₹{corpus}</b> தேவை. தற்போது உங்களிடம் ₹{port} உள்ளது.',
        fire_adv_short: '⚠️ உங்களின் தற்போதைய ₹{sip} SIP முதலீடு {years} ஆண்டுகளில் ₹{corpus}-ஐ அடையப் போதாது. மாதத்திற்கு ₹{reqSip} ஆக நீங்கள் அதிகரிக்க வேண்டும் (12% ஊகிக்கப்பட்ட வருமானம்).',
        fire_adv_good: '✅ சிறப்பு! உங்களின் நடப்பு ₹{sip} SIP முதலீடு {years} ஆண்டுகளில் ₹{corpus} இலக்கை எளிதில் அடையும்.',
        fire_adv_safe: '🛡️ பாதுகாப்பு: ஓய்வுபெறும் 3 ஆண்டுகளுக்கு முன்பு உங்கள் 3 வருட செலவை (₹{safe}) பங்குச்சந்தையிலிருந்து பாதுகாப்பான FD-க்கு மாற்றவும்.',
        fire_adv_ins: '🏥 உடல்நலக் காப்பீடு: 45 வயதிற்கு முன்னதாக உங்கள் மருத்துவக் காப்பீட்டை Super Top-up திட்டமாக மாற்றவும்.',
        life_verd_bonus: '💼 <b>போனஸ் விநியோகம்:</b> 10% (₹{fun})-ஐ மகிழ்ச்சியாகச் செலவிடுங்கள்! 30% (₹{tax})-ஐ அதிக வட்டி உள்ள கடன்களை அடைக்க பயன்படுத்துங்கள். மீதமுள்ள 60% (₹{inv})-ஐ பங்குச்சந்தை (MF) முதலீட்டில் சேர்க்கவும்.',
        life_verd_inherit: '🏛️ <b>மொத்த பணம்:</b> உடனே அந்த ₹{amt}-ஐ செலவிட வேண்டாம். 6 மாதங்கள் அதனை Liquid Fund-ல் வைக்கவும். பின்பு 12 மாத கால அளவில் STP மூலம் Index Fund-ல் சிறிது சிறிதாக முதலீடு செய்யவும்.',
        life_verd_marriage: '💍 <b>திருமணம்:</b> 1. உங்கள் இருவரின் வருமானத்தையும் இணைத்து நிர்வகியுங்கள். 2. Family Floater Health காப்பீடு எடுக்கவும். 3. அனைத்து முதலீடுகளிலும் உங்கள் துணையை Nominee-யாக சேர்க்கவும்.',
        life_verd_baby: '🍼 <b>குழந்தை:</b> 1. குழந்தையின் பாதுகாப்பிற்காக உடனடியாக ஒரு Term Insurance வாங்கவும் (15x). 2. குழந்தையின் கல்விக்காக Flexi-cap Fund-ல் SIP தொடங்கவும் (18 வருட இலக்கு). 3. காப்பீட்டில் குழந்தையைச் சேர்க்கவும்.',
        tab_rent: '🏠 வாடகை vs வாங்குவது',
        rent_title: '<span class="gradient-text">நிலம்</span> மற்றும் வீடு மதிப்பீட்டாளர்', rent_desc: 'AI கணிதம்: வீட்டை வாங்குவது நல்லதா அல்லது வாடகைக்கு இருந்து பணத்தை முதலீடு செய்வது நல்லதா?',
        rent_lbl_cost: 'சொத்து மதிப்பு (₹)', rent_lbl_dp: 'முன்பணம் (Down Payment) (₹)', rent_lbl_roi: 'வீட்டுக் கடன் வட்டி விகிதம் (%)',
        rent_lbl_tenure: 'கடன் காலம் (ஆண்டுகள்)', rent_lbl_rent: 'தற்போதைய மாத வாடகை (₹)', rent_lbl_prop_app: 'சொத்து மதிப்பு உயர்வு (ஆண்டுக்கு %)',
        rent_lbl_mf_ret: 'எதிர்பார்க்கும் MF லாபம் (ஆண்டுக்கு %)', rent_btn_run: 'எதிர்காலத்தை கணக்கிடு 🔮',
        rent_res_title: '🏢 வாங்குவது vs வாடகை (Net Worth)',
        rent_verd_buy: '💡 <b>வாங்குவதே சிறந்தது!</b> {years} ஆண்டுகளுக்குப் பிறகு, வீட்டை வாங்குவதன் மூலம் உங்கள் நிகர மதிப்பு <b>₹{buyNw}</b> ஆக இருக்கும், ஆனால் வாடகைக்கு இருந்தால் <b>₹{rentNw}</b> மட்டுமே. சொத்து மதிப்பு உயர்வு உங்களுக்கு சாதகமாக அமைந்தது.',
        rent_verd_rent: '💡 <b>வாடகையே சிறந்தது!</b> {years} ஆண்டுகளுக்குப் பிறகு, வாடகைக்கு இருந்து முதலீடு செய்தால் உங்கள் நிகர மதிப்பு <b>₹{rentNw}</b> ஆக இருக்கும், ஆனால் வீட்டை வாங்கினால் <b>₹{buyNw}</b> மட்டுமே. Mutual Fund-ன் கூட்டு வட்டி வென்றது.',
        rent_adv_emi: '🏦 <b>EMI செலவு:</b> உங்களின் உத்தேச EMI ₹{emi}. தற்போதைய வாடகை ₹{rent}. மீதமுள்ள ₹{diff} ஒவ்வொரு மாதமும் MF-ல் முதலீடு செய்யப்படும்.',
        rent_adv_tax: '⚖️ <b>வரிச் சலுகை:</b> வீடு வாங்கினால் Section 24(b) (₹2L வட்டி விலக்கு) மற்றும் 80C (₹1.5L முதலீடு) வரிவிலக்கு கிடைக்கும். இதனால் EMI சுமை சற்றே குறையும்.',
        rent_adv_flex: '🚶‍♂️ <b>சுதந்திரம் (Flexibility):</b> வாடகைக்கு இருப்பது வேலை மாறுபவர்களுக்கு எளிதானது மற்றும் சொத்து வரி/பராமரிப்பு (ஆண்டுக்கு 1%) செலவுகளும் கிடையாது.',
        tab_debt: '💳 கடன் தீர்க்கும் கருவி',
        debt_title: '<span class="gradient-text">கடன்</span> தீர்க்கும் கருவி', debt_desc: 'உங்களது EMI-ஐ AI மூலம் திட்டமிட்டு சில ஆண்டுகள் முன்னதாகவே கடன் சுமையிலிருந்து விடுபடுங்கள்.',
        debt_lbl_l1_bal: 'கடன் 1: மீதமுள்ள தொகை (₹)', debt_lbl_l1_roi: 'கடன் 1: வட்டி விகிதம் (%)', debt_lbl_l1_emi: 'கடன் 1: தற்போதைய EMI (₹)',
        debt_lbl_l2_bal: 'கடன் 2: மீதமுள்ள தொகை (₹)', debt_lbl_l2_roi: 'கடன் 2: வட்டி விகிதம் (%)', debt_lbl_l2_emi: 'கடன் 2: தற்போதைய EMI (₹)',
        debt_lbl_extra: 'மாதாந்திர கூடுதல் தொகை (₹)', debt_btn_run: 'விரைவான வழியைக் கண்டறி ⚡',
        debt_res_title: '💳 AI கடன் வியூகம்',
        debt_verd_time_saved: '💡 <b>Avalanche முறையைப் பயன்படுத்தி</b> மாதம் ₹{extra} கூடுதலாகச் செலுத்தினால், {oldMonths} மாதங்களுக்குப் பதிலாக <b>{newMonths} மாதங்களில்</b> முழுமையாகக் கடனிலிருந்து விடுபடுவீர்கள்! ({diffMonths} மாதங்கள் சேமிப்பு).',
        debt_verd_int_saved: '💡 மொத்த வட்டிச் செலவு ₹{oldInt} லிருந்து <b>₹{newInt}</b> ஆக குறையும். இது <b>₹{diffInt}</b> நேரடிச் சேமிப்பாகும்!',
        debt_adv_avalanche: '📈 <b>Avalanche வியூகம்:</b> குறைந்தபட்ச EMI தொகையை மட்டும் கட்டுங்கள். மீதமுள்ள பணத்தை அதிக வட்டி உள்ள கடனை அடைக்க மட்டும் பயன்படுத்துங்கள். ஒரு கடன் முடிந்தவுடன், அந்த EMI-ஐ அடுத்த கடனுடன் சேர்த்து கட்டுங்கள்.',
        debt_adv_warning: '⚠️ <b>எச்சரிக்கை:</b> கடனுக்கான வட்டி 12%-க்கு மேல் இருந்தால், முதலீடுகளைத் தவிர்த்துவிட்டு முதலில் கடனை முழுமையாக அடைப்பதில் கவனம் செலுத்துங்கள்.',
        tab_gold: '🥇 தங்கம் (SGB) பகுப்பாய்வு',
        gold_title: '<span class="gradient-text">தங்கம்</span> பகுப்பாய்வு', gold_desc: 'அசல் தங்கத்திற்கும் (Physical) SGB-க்கும் உள்ள ரகசிய நஷ்டங்கள் மற்றும் லாபங்களைக் கணக்கிடுங்கள்.',
        gold_lbl_port: 'மொத்த சொத்து மதிப்பு (Net Worth) (₹)', gold_lbl_phys: 'நகைகள் / தங்க நாணயங்கள் மதிப்பு (₹)', gold_lbl_sgb: 'SGB / தங்க ETF மதிப்பு (₹)',
        gold_btn_run: 'தங்கத்தை பகுப்பாய்வு செய் 🔎', gold_res_title: '🥇 AI தங்க வியூகம்',
        gold_verd_alloc_good: '✅ <b>சிறந்த விகிதம்:</b> உங்களின் தங்கம் மொத்த சொத்தில் {pct}% உள்ளது. இது 10-15% என்ற பாதுகாப்பான எல்லைக்குள் உள்ளது.',
        gold_verd_alloc_bad: '⚠️ <b>எச்சரிக்கை:</b> தங்கம் உங்களின் மொத்த சொத்தில் {pct}% உள்ளது! இது மிக அதிகம். தங்கம் செல்வத்தை பெருக்காது, பாதுகாக்கும் மட்டுமே (Keep < 15%).',
        gold_verd_loss: '💡 SGB-க்கு பதிலாக ₹{amount}-க்கு நகையாக 8 ஆண்டுகள் வைத்திருந்தால், உங்களுக்கு ~<b>₹{loss}</b> மறைமுக நஷ்டம் ஏற்படும்! (செய்கூலி/சேதாரம் மற்றும் வரி).',
        gold_verd_sgb: '💡 நீங்கள் SGB-யில் முதலீடு செய்துள்ளதால், 8 ஆண்டுகளில் ₹{interest} கூடுதல் வட்டி வரி-இல்லாமல் கிடைக்கும்!',
        gold_adv_sgb: '📈 <b>SGB விதிகள்:</b> முதலீட்டிற்காக ஒருபோதும் அசலை வாங்காதீர்கள். ரிசர்வ் வங்கியிடம் Sovereign Gold Bonds (SGB) வாங்குவதன் மூலம் 2.5% கூடுதல் வட்டி மற்றும் வரிவிலக்கு கிடைக்கும்.',
        gold_adv_limit: '🚫 <b>பன்முகத்தன்மை:</b> நகைகளை ஒருபோதும் தகுதியான முதலீடாக நினைக்க வேண்டாம். உண்மையான செல்வத்தை உருவாக்க Mutual Funds-ல் முதலீடு செய்யுங்கள்.'
    }
};

window.i18n = i18n;
